package com.example.models;
// Generated Dec 5, 2019 11:21:42 AM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private Integer addressId;
	private String address;
	private Set<Customer> customers = new HashSet<Customer>(0);

	public Address() {
	}
	public Address(Integer addressId) {
		this.addressId=addressId;
	}

	public Address(String address) {
		this.address = address;
	}

	public Address(String address, Set<Customer> customers) {
		this.address = address;
		this.customers = customers;
	}

	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

}
