package com.example.models;
// Generated Dec 5, 2019 11:21:42 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

	private Integer adminId;
	private String name;
	private String mail;
	private String pwd;
	private String gender;
	private Date createDate;
	private Set<Store> storesForAdminId = new HashSet<Store>(0);
	private Set<Store> storesForGoldAdminId = new HashSet<Store>(0);
	private Set<Role> roles = new HashSet<Role>(0);

	public Admin() {
	}

	public Admin(String name, String mail, String pwd, String gender, Date createDate) {
		this.name = name;
		this.mail = mail;
		this.pwd = pwd;
		this.gender = gender;
		this.createDate = createDate;
	}

	public Admin(String name, String mail, String pwd, String gender, Date createDate, Set<Store> storesForAdminId,
			Set<Store> storesForGoldAdminId, Set<Role> roles) {
		this.name = name;
		this.mail = mail;
		this.pwd = pwd;
		this.gender = gender;
		this.createDate = createDate;
		this.storesForAdminId = storesForAdminId;
		this.storesForGoldAdminId = storesForGoldAdminId;
		this.roles = roles;
	}

	public Integer getAdminId() {
		return this.adminId;
	}

	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Set<Store> getStoresForAdminId() {
		return this.storesForAdminId;
	}

	public void setStoresForAdminId(Set<Store> storesForAdminId) {
		this.storesForAdminId = storesForAdminId;
	}

	public Set<Store> getStoresForGoldAdminId() {
		return this.storesForGoldAdminId;
	}

	public void setStoresForGoldAdminId(Set<Store> storesForGoldAdminId) {
		this.storesForGoldAdminId = storesForGoldAdminId;
	}

	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

}
