package com.example.models;
// Generated Dec 5, 2019 11:21:42 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private Integer customerId;
	private Address address;
	private String name;
	private String male;
	private String phone;
	private Date createDate;
	private Set<Store> stores = new HashSet<Store>(0);

	public Customer() {
	}
	public Customer(int customerId) {
		this.customerId=customerId;
	}
	public Customer(Address address, String name, String male, String phone) {
		this.address = address;
		this.name = name;
		this.male = male;
		this.phone = phone;
	}

	public Customer(Address address, String name, String male, String phone, Date createDate, Set<Store> stores) {
		this.address = address;
		this.name = name;
		this.male = male;
		this.phone = phone;
		this.createDate = createDate;
		this.stores = stores;
	}

	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMale() {
		return this.male;
	}

	public void setMale(String male) {
		this.male = male;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Set<Store> getStores() {
		return this.stores;
	}

	public void setStores(Set<Store> stores) {
		this.stores = stores;
	}

}
