package com.example.models;
// Generated Dec 12, 2019 11:26:46 PM by Hibernate Tools 4.0.1.Final

/**
 * StorePerLitter generated by hbm2java
 */
public class StorePerLitter implements java.io.Serializable {

	private int storePerLitterId;
	private Store store;
	private double litter;
	private double pound;

	public StorePerLitter() {
	}

	public StorePerLitter(int storePerLitterId, Store store, double litter, double pound) {
		this.storePerLitterId = storePerLitterId;
		this.store = store;
		this.litter = litter;
		this.pound = pound;
	}

	public int getStorePerLitterId() {
		return this.storePerLitterId;
	}

	public void setStorePerLitterId(int storePerLitterId) {
		this.storePerLitterId = storePerLitterId;
	}

	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	public double getLitter() {
		return this.litter;
	}

	public void setLitter(double litter) {
		this.litter = litter;
	}

	public double getPound() {
		return this.pound;
	}

	public void setPound(double pound) {
		this.pound = pound;
	}

}
