package com.example.models;
// Generated Dec 12, 2019 11:26:46 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Store generated by hbm2java
 */
public class Store implements java.io.Serializable {

	private Integer storeId;
	private Customer customer;
	private Admin adminByGoldAdminId;
	private Admin adminByAdminId;
	private double waterLitter;
	private double drc;
	private double totalLitter;
	private double dryPound;
	private Date createDate;
	private double totalPound;
	private Set<StorePerLitter> storePerLitters= new HashSet<StorePerLitter>(0);

	public Store() {
	}

	public Store(Customer customer, Admin adminByGoldAdminId, Admin adminByAdminId, double waterLitter, double drc,
			double totalLitter, double dryPound, Date createDate) {
		this.customer = customer;
		this.adminByGoldAdminId = adminByGoldAdminId;
		this.adminByAdminId = adminByAdminId;
		this.waterLitter = waterLitter;
		this.drc = drc;
		this.totalLitter = totalLitter;
		this.dryPound = dryPound;
		this.createDate = createDate;
	}

	public Store(Customer customer, Admin adminByGoldAdminId, Admin adminByAdminId, double waterLitter, double drc,
			double totalLitter, double dryPound, Date createDate, Set<StorePerLitter> storePerLitters) {
		this.customer = customer;
		this.adminByGoldAdminId = adminByGoldAdminId;
		this.adminByAdminId = adminByAdminId;
		this.waterLitter = waterLitter;
		this.drc = drc;
		this.totalLitter = totalLitter;
		this.dryPound = dryPound;
		this.createDate = createDate;
		this.storePerLitters = storePerLitters;
	}

	public Integer getStoreId() {
		return this.storeId;
	}

	public void setStoreId(Integer storeId) {
		this.storeId = storeId;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Admin getAdminByGoldAdminId() {
		return this.adminByGoldAdminId;
	}

	public void setAdminByGoldAdminId(Admin adminByGoldAdminId) {
		this.adminByGoldAdminId = adminByGoldAdminId;
	}

	public Admin getAdminByAdminId() {
		return this.adminByAdminId;
	}

	public void setAdminByAdminId(Admin adminByAdminId) {
		this.adminByAdminId = adminByAdminId;
	}

	public double getWaterLitter() {
		return this.waterLitter;
	}

	public void setWaterLitter(double waterLitter) {
		this.waterLitter = waterLitter;
	}

	public double getDrc() {
		return this.drc;
	}

	public void setDrc(double drc) {
		this.drc = drc;
	}

	public double getTotalLitter() {
		return this.totalLitter;
	}

	public void setTotalLitter(double totalLitter) {
		this.totalLitter = totalLitter;
	}

	public double getDryPound() {
		return this.dryPound;
	}

	public void setDryPound(double dryPound) {
		this.dryPound = dryPound;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Set<StorePerLitter> getStorePerLitters() {
		return this.storePerLitters;
	}

	public double getTotalPound() {
		return totalPound;
	}

	public void setTotalPound(double totalPound) {
		this.totalPound = totalPound;
	}

	public void setStorePerLitters(Set<StorePerLitter> storePerLitters) {
		this.storePerLitters = storePerLitters;
	}

}
